# Generated by Django 3.2 on 2021-04-20 13:59

import boards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=32, verbose_name='기관/회사명')),
                ('manager', models.CharField(max_length=8, verbose_name='담당자명')),
                ('phone', models.CharField(max_length=16, verbose_name='연락처')),
                ('title', models.CharField(max_length=32, verbose_name='제목')),
                ('email', models.EmailField(max_length=32, verbose_name='E-mail')),
                ('explanation', models.TextField(verbose_name='프로젝트 설명')),
                ('budget', models.CharField(choices=[('UD', '미정'), ('U1', '500만원~1000만원'), ('U3', '1000만원~3000만원'), ('U5', '3000만원~5000만원'), ('U10', '5000만원~1억원'), ('O10', '1억원 이상')], max_length=3, verbose_name='예산')),
                ('expected_period', models.CharField(choices=[('U2', '1~2개월'), ('U5', '3~5개월'), ('U9', '6~9개월'), ('O9', '9개월 이상')], max_length=2, verbose_name='예상 기간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=boards.models.get_file_path)),
                ('isDel', models.BooleanField(default=False)),
                ('originName', models.CharField(max_length=128)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='boards.board')),
            ],
        ),
    ]
