version: "3"

services:
  db:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "soulware"
    ports:
      - "3306:3306"
  web:
    build: ./web_proj
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
  client:
    build: ./front_proj
    volumes:
      - ./front_proj:/front
    ports:
      - "8080:8080"
