# Generated by Django 3.1.7 on 2021-03-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('body', models.TextField(verbose_name='본문')),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('isDel', models.BooleanField(default=False)),
                ('originName', models.CharField(max_length=128)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='boards.board')),
            ],
        ),
    ]
