# Generated by Django 3.1.7 on 2021-03-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20210318_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='files',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
